### ISSUE TITLE
Orientar a implementação do banco de dados.

### ISSUE THREAD

**Issue by Brownlius** [InsDevs-LTDA/projeto-ava-insted#3]
- Para o desenvolvimento do modelo conceitual do banco de dados deverá ser construído um Diagrama Entidade-Relacionamento (DER).

- Dicionário de dados.

[Dicionario de dados - Area Insted.pdf](https://github.com/InsDevs-LTDA/projeto-ava-insted/files/11054059/Dicionario.de.dados.-.Area.Insted.pdf)

[Scripts do BD.zip](https://github.com/InsDevs-LTDA/projeto-ava-insted/files/11054062/Scripts.do.BD.zip)

Arquivo para adicionar as FKs:
[ALTERS TB - FK.txt](https://github.com/InsDevs-LTDA/projeto-ava-insted/files/11055062/ALTERS.TB.-.FK.txt)

Arquivo para adicionar as Tables:
[CREATE DB E TBs.txt](https://github.com/InsDevs-LTDA/projeto-ava-insted/files/11055063/CREATE.DB.E.TBs.txt)

**Comment by deborahsakamoto** [comment]
Primeiro realizar o script de criação de todas as tabelas, o circulado em vermelho. Depois de todas as tabelas criadas. criar o relacionamento delas (marcação amarela/laranja). Por último realizar o script da trigger
![script](https://user-images.githubusercontent.com/101063568/227316601-1172d3ce-0d72-4af7-8bc1-6b3c917fc2e2.PNG)
